apiVersion: v1
kind: Pod
metadata:
  name: my-config-pod
spec:
  containers:
  - name: myctr
    image: busybox
    command: ['sh','-c','echo $(myvalue) && sleep 3600']
    env:
      - name: myvalue
        valueFrom:
         configMapKeyRef:
           name: literal-config
           key: myName
    
